### ISSUE TITLE
Don't add `html` selector

### ISSUE THREAD

**Issue by Garbee** [gasolin/postcss-bidirection#7]
Adding `html` increases specificity more and only allows targeting of the component if the page itself is in RTL/LTR mode. However, the `dir` attribute can be used on any given element really. Therefore an inner page node could be `rtl` while the parent document is `ltr`. Which means the output provided won't hit an element inside of a node with changed direction. Where a generic `[dir="rtl"] .whatever` type selector will hit it just fine.

**Comment by gasolin** [comment]
I haven't encounter a situation that `inner page node could be rtl while the parent document is ltr`. Could you point out a real world sample so we can investigate on it? :)

**Comment by Garbee** [comment]
I don't think it occurs in general sites often, if at all. I have seen some people bring up issues with other things where they're building demos and they mix directions to show off functionality. I just noticed the output here requires one strict direction on the entire document for things to work when that isn't what the specifications require. They simply care about the current nodes directionality, much like the `:dir` [psuedo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir). It seems best to me to allow developers to build the output they want. This would however require rules target two things now that I think of it,

```css
[dir="rtl"] .whatever,
.whatever[dir="rtl"] {}
```

Is there any reason to restrict it only to the `html` node? I simply see it as working in a very strict way where the specs allow for more leniency in changing the direction of the content.

**Comment by rolfen** [comment]
> I haven't encounter a situation that inner page node could be rtl while the parent document is ltr. 

This doesn't mean that it can't happen. Don't make any assumptions! Why not just follow the HTML spec? It can't be too hard to drop the html from `html` from the prefix string.

Anyway, it happens on a site that I'm working on - we have not localized the whole page yet (with the menu, footers and all), but we want one section of the page to display property (with the arabic text being properly aligned), so the dir attribute is set on a div or two.

**Comment by gasolin** [comment]
@rolfen I'd like to accept generate different outputs. If you can pass some params/options to change the final output, we can merge the work in the same repo.

**Comment by rolfen** [comment]
@gasolin - Thank you. I think a callback function to customize output would be good - I saw this in another similar project.

**Comment by rolfen** [comment]
Changing the prefix fails all the tests. Any idea how to solve that?

**Comment by gasolin** [comment]
current plugin accept an object `{}` as options.
https://github.com/gasolin/postcss-bidirection/blob/master/index.js#L158

You can pass and parse the option here and control the output at the related place.

**Comment by rolfen** [comment]
Hello! Should this issue not be closed?
